### ISSUE TITLE
Access Denied on SMB connection using "pi"

### ISSUE THREAD

**Issue by tobilabs** [LePopal/SMBv1-Gateway#1]
I'm getting "Access Denied" when trying to connect to the device using the credentials for the user pi. Did I do something wrong?

**Comment by LePopal** [comment]
The default password is "raspberry". Be sure to check your keyboard layout

Le mar. 25 mai 2021 à 13:59, Tobias Schlienger ***@***.***> a
écrit :

**Comment by tobilabs** [comment]
To make sure I am doing everything right I reinstalled your Image on my Raspberry and tried to login using SMB on my Windows machine (I previously enabled SMB v1 in the optional Features). Getting the same result as in the Sonos Controller Application. I would really like to help resolve this issue, assuming the problem is not on my side.
![image](https://user-images.githubusercontent.com/11772968/119678481-d58df700-be3f-11eb-9e06-45536809efac.png)

**Comment by LePopal** [comment]
Oh I see ! I'm sorry, I forgot to specify the default user/password on the SMBv1 side. 

I updated the readme with the username (which is 'music') and how to reset it using sudo smbpasswd music

**Comment by tobilabs** [comment]
Ohhh okay! I found this user when looking through the passwd file, but assumed it was a leftover and not needed, since it wasn't added to any user group used by the SMB share. Thank you very much, I will try your solution tonight, didn't know there were separate "change password" commands for the console and SMB (this probably explains my previous issues setting up SMB shares on other devices...)

**Comment by tobilabs** [comment]
Hello there, just tried your new guide and it worked like a charm! Thank you very much for this project, you're saving me a lot of time creating this solution myself.

**Comment by LePopal** [comment]
Awesome ! I'm glad I can be of some help.
I'm using this solution for several months now and it works like a charm
for my Sonos.

Le mar. 1 juin 2021 à 19:16, Tobias Schlienger ***@***.***> a
écrit :
